```yaml
name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: irinemilton

          template: classic
          base: header, activity, community, repositories, metadata

          config_timezone: Asia/Kolkata

          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_ignored: html, css

          plugin_isocalendar: yes
          plugin_achievements: yes
          plugin_followup: yes
          plugin_lines: yes
          plugin_stars: yes
```
